name: C/C++ CI

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && ../configure && make && sudo make install

